name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: aarch64
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
    - name: Prepare system
      shell: bash
      run: |
        apt update
        apt -y full-upgrade
        apt -y install git
    - name: Check out source
      uses: actions/checkout@v1
    - name: Install dependencies
      shell: bash
      run: |
        dpkg --add-architecture arm64
        sh -c "sed \"s|^deb \([a-z\.:/]*\) \([a-z\-]*\) \(.*\)$|deb [arch=amd64] \1 \2 \3\ndeb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports \2 \3|\" /etc/apt/sources.list > /etc/apt/sources.list.new"
        rm /etc/apt/sources.list
        mv /etc/apt/sources.list{.new,}
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y {gcc-12,g++-12}-aarch64-linux-gnu {libsdl2,qt6-{base,base-private,multimedia},libslirp,libarchive,libzstd}-dev:arm64 pkg-config zstd:arm64 cmake extra-cmake-modules dpkg-dev
    - name: Configure
      shell: bash
      run: |
        cmake -B build \
          -DPKG_CONFIG_EXECUTABLE=/usr/bin/aarch64-linux-gnu-pkg-config \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc-12 \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++-12 \
          -DUSE_QT6=ON
    - name: Make
      shell: bash
      run: |
        cmake --build build -j$(nproc --all)
        mkdir dist
        cp build/melonDS dist
    - uses: actions/upload-artifact@v1
      with:
        name: melonDS-ubuntu-aarch64
        path: dist
