name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: x86_64
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt update
        sudo apt install cmake extra-cmake-modules libpcap0.8-dev libsdl2-dev qtbase6-dev qtbase6-private-dev qtmultimedia6-dev libslirp0 libslirp-dev libarchive-dev libzstd-dev --allow-downgrades
    - name: Create build environment
      run: mkdir ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DUSE_QT6=ON
    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j$(nproc --all)
        mkdir dist
        cp melonDS dist
    - uses: actions/upload-artifact@v1
      with:
        name: melonDS-ubuntu-x86_64
        path: ${{runner.workspace}}/build/dist
