name: AppImage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt update
        sudo apt install cmake extra-cmake-modules libpcap0.8-dev libsdl2-dev qt6-{base,base-private,multimedia,tools}-dev qt6-qpa-plugins libslirp0 libslirp-dev libarchive-dev libzstd-dev --allow-downgrades libfuse2
    - name: Create build environment
      run: mkdir ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DUSE_QT6=ON
    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j$(nproc --all)
    - name: Prepare AppDir for AppImage
      working-directory: ${{runner.workspace}}/build
      run: |
        make install DESTDIR=AppDir
        mv ./AppDir/usr/local/bin ./AppDir/usr/bin
        mv ./AppDir/usr/local/share ./AppDir/usr/share
        rm -rf ./AppDir/usr/local
    - name: Prepare necessary Tools for building the AppImage
      working-directory: ${{runner.workspace}}/build
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        chmod a+x linuxdeploy-x86_64.AppImage
        chmod a+x linuxdeploy-plugin-qt-x86_64.AppImage
    - name: Build the AppImage
      working-directory: ${{runner.workspace}}/build
      env:
        QMAKE: /usr/lib/qt6/bin/qmake
      run: |
        ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
        mkdir dist
        cp ./melonDS*.AppImage ./dist
    - uses: actions/upload-artifact@v1
      with:
        name: melonDS-appimage-x86_64
        path: ${{runner.workspace}}/build/dist
